#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.5 on Sat May  2 19:38:00 2020
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((600, 400))
        self.info_Panel = wx.Panel(self, wx.ID_ANY)
        self.info_Notebook = wx.Notebook(self.info_Panel, wx.ID_ANY)
        self.info_Notebook_Menu = wx.Panel(self.info_Notebook, wx.ID_ANY)
        self.info_Notebook_Modo = wx.Panel(self.info_Notebook, wx.ID_ANY)
        self.radio_btn_1 = wx.RadioButton(self.info_Notebook_Modo, wx.ID_ANY, "Alfabetico")
        self.radio_btn_2 = wx.RadioButton(self.info_Notebook_Modo, wx.ID_ANY, "Nivel")
        self.radio_btn_3 = wx.RadioButton(self.info_Notebook_Modo, wx.ID_ANY, "1024")
        self.radio_btn_4 = wx.RadioButton(self.info_Notebook_Modo, wx.ID_ANY, "2048")
        self.grid_Panel = wx.Panel(self, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("frame")
        self.radio_btn_1.SetValue(1)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        grid_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        info_Sizer = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_4.Add(self.radio_btn_1, 0, 0, 0)
        sizer_4.Add(self.radio_btn_2, 0, 0, 0)
        sizer_4.Add(self.radio_btn_3, 0, 0, 0)
        sizer_4.Add(self.radio_btn_4, 0, 0, 0)
        self.info_Notebook_Modo.SetSizer(sizer_4)
        self.info_Notebook.AddPage(self.info_Notebook_Menu, "Menu")
        self.info_Notebook.AddPage(self.info_Notebook_Modo, "Modo")
        info_Sizer.Add(self.info_Notebook, 1, wx.EXPAND, 0)
        self.info_Panel.SetSizer(info_Sizer)
        sizer_1.Add(self.info_Panel, 1, wx.EXPAND, 0)
        grid_Sizer.Add((0, 0), 0, 0, 0)
        self.grid_Panel.SetSizer(grid_Sizer)
        sizer_1.Add(self.grid_Panel, 3, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class MainFrame

class Window(wx.App):
    def OnInit(self):
        self.main_Frame = MainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.main_Frame)
        self.main_Frame.Show()
        return True

# end of class Window

