#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.5 on Sun May 10 13:36:18 2020
#
import windowController
import wx


# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        self.keyActivated = None
        self.tiles = windowController.setGrid(4, 2)
        self.score = 0
        self.moves = 0
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((900, 600))
        self.options_Panel = wx.Panel(self, wx.ID_ANY)
        self.mode_Button = wx.Button(self.options_Panel, wx.ID_ANY, "Change Mode")
        self.save_Button = wx.Button(self.options_Panel, wx.ID_ANY, "Save Game")
        self.menu_Button = wx.Button(self.options_Panel, wx.ID_ANY, "Main Menu")
        self.data_Panel = wx.Panel(self, wx.ID_ANY)
        self.grid_Panel = wx.Panel(self, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.on_change_mode, self.mode_Button)
        self.Bind(wx.EVT_BUTTON, self.on_save_game, self.save_Button)
        self.Bind(wx.EVT_BUTTON, self.on_main_menu, self.menu_Button)
        self.Bind(wx.EVT_KEY_DOWN, self.onKeyPress)
        self.Bind(wx.EVT_KEY_UP, self.onKeyRelease)
        self.Bind(wx.EVT_CHAR, self.onKeyPress)
        # end wxGlade

        self.addData(self.score, self.moves)
        self.addGrid()
        self.SetFocus()

    def addGrid(self):
        grid = wx.GridSizer(len(self.tiles), len(self.tiles), 5, 5)
        print("Cols " + str(grid.GetCols()))
        for i in range(len(self.tiles)):
            for j in range(len(self.tiles)):
                label = wx.StaticText(self.grid_Panel)
                label.SetLabel(self.tiles[j][i].getDisplayValue())
                grid.Add(label, 1, wx.EXPAND, 5)
        self.grid_Panel.SetSizer(grid)
        self.Layout()

    def addData(self, score, moves):
        print("Score:", score)
        print("Moves:", moves)
        dataSizer = wx.BoxSizer(wx.VERTICAL)
        scoreLbl = wx.StaticText(self.data_Panel)
        scoreLbl.SetLabel("Score: " + str(score))
        dataSizer.Add(scoreLbl)
        movesLbl = wx.StaticText(self.data_Panel)
        movesLbl.SetLabel("Moves: " + str(moves))
        dataSizer.Add(movesLbl)
        self.data_Panel.SetSizer(dataSizer)
        self.Layout()

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("2048py Game")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        options_Sizer = wx.BoxSizer(wx.VERTICAL)
        options_Sizer.Add(self.mode_Button, 1, wx.ALL | wx.EXPAND, 4)
        options_Sizer.Add(self.save_Button, 1, wx.ALL | wx.EXPAND, 4)
        options_Sizer.Add(self.menu_Button, 1, wx.ALL | wx.EXPAND, 4)
        self.options_Panel.SetSizer(options_Sizer)
        sizer_3.Add(self.options_Panel, 1, wx.EXPAND, 0)
        sizer_3.Add(self.data_Panel, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_1.Add(self.grid_Panel, 4, wx.ALL | wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def on_change_mode(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'on_change_mode' not implemented!")
        event.Skip()

    def on_save_game(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'on_save_game' not implemented!")
        event.Skip()

    def on_main_menu(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'on_main_menu' not implemented!")

    def onKeyPress(self, event):
        keycode = event.GetKeyCode()
        print("KeyPressed: " + str(keycode))
        if keycode == 87:
            self.tiles, self.score = windowController.movement("W", self.score, self.tiles)
            windowController.addValue(self.tiles)
        elif keycode == 65:
            self.tiles, self.score = windowController.movement("A", self.score, self.tiles)
            windowController.addValue(self.tiles)
        elif keycode == 83:
            self.tiles, self.score = windowController.movement("S", self.score, self.tiles)
            windowController.addValue(self.tiles)
        elif keycode == 68:
            self.tiles, self.score = windowController.movement("D", self.score, self.tiles)
            windowController.addValue(self.tiles)
        self.addData(self.score, self.moves)
        self.addGrid()
        self.Layout()

    def onKeyRelease(self, event):
        keycode = event.GetKeyCode()
        #print("KeyReleased: " + str(keycode))
        self.keyActivated = None

    def getKey(self):
        return self.keyActivated


# end of class MainFrame

class MenuFrame(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MenuFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((200, 300))
        self.newGameButton = wx.Button(self, wx.ID_ANY, "Start new game")
        self.loadGameButton = wx.Button(self, wx.ID_ANY, "Load game")
        self.exitGameButton = wx.Button(self, wx.ID_ANY, "Exit game")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.on_start_game, self.newGameButton)
        self.Bind(wx.EVT_BUTTON, self.on_load_game, self.loadGameButton)
        self.Bind(wx.EVT_BUTTON, self.on_exit_game, self.exitGameButton)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MenuFrame.__set_properties
        self.SetTitle("Main Menu")
        self.SetSize((200, 300))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MenuFrame.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(self.newGameButton, 1, wx.ALL | wx.EXPAND, 5)
        sizer_2.Add(self.loadGameButton, 1, wx.ALL | wx.EXPAND, 5)
        sizer_2.Add(self.exitGameButton, 1, wx.ALL | wx.EXPAND, 5)
        self.SetSizer(sizer_2)
        self.Layout()
        # end wxGlade

    def on_start_game(self, event):  # wxGlade: MenuFrame.<event_handler>
        print("Event handler 'on_start_game' not implemented!")
        event.Skip()

    def on_load_game(self, event):  # wxGlade: MenuFrame.<event_handler>
        print("Event handler 'on_load_game' not implemented!")
        event.Skip()

    def on_exit_game(self, event):  # wxGlade: MenuFrame.<event_handler>
        print("Event handler 'on_exit_game' not implemented!")
        event.Skip()


# end of class MenuFrame

class LoadFrame(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: LoadFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((300, 200))
        self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.loadSavedGameButton = wx.Button(self, wx.ID_ANY, "Load")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.on_load_saved_game, self.loadSavedGameButton)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: LoadFrame.__set_properties
        self.SetTitle("Load Saved Game")
        self.SetSize((300, 200))
        self.text_ctrl_1.SetMinSize((250, 30))
        self.loadSavedGameButton.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: LoadFrame.__do_layout
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        label_1 = wx.StaticText(self, wx.ID_ANY, u"Enter the saved game´s name")
        label_1.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_4.Add(label_1, 0, wx.ALIGN_CENTER | wx.ALL, 6)
        sizer_4.Add(self.text_ctrl_1, 0, wx.ALIGN_CENTER | wx.ALL, 10)
        sizer_4.Add(self.loadSavedGameButton, 1, wx.ALIGN_CENTER | wx.ALL, 5)
        self.SetSizer(sizer_4)
        self.Layout()
        # end wxGlade

    def on_load_saved_game(self, event):  # wxGlade: LoadFrame.<event_handler>
        print("Event handler 'on_load_saved_game' not implemented!")
        event.Skip()


# end of class LoadFrame

class Window(wx.App):
    def OnInit(self):
        self.main_Frame = MainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.main_Frame)
        self.main_Frame.Show()
        return True


# end of class Window

if __name__ == "__main__":
    app = Window(0)
    app.MainLoop()
